document.getElementsByTagName("h1")[0].innerHTML = '来店予約';
document.getElementsByTagName("h2")[0].innerHTML = '私たちのオフィスはゲートウェイ、ハーバーシティ、尖沙咀にある、どのような交通手段でも簡単に来れます。';
document.getElementsByTagName("p")[4].innerHTML = '営業時間は平日の午前9時から午後9時です。';
document.getElementsByTagName("p")[5].innerHTML = '弊社のCS担当は、口座開設や、取引ツール、その他のお問い合わせに関して、一対一でご説明いたします。';
document.getElementsByTagName("p")[6].innerHTML = '';
document.getElementsByTagName("p")[8].innerHTML = '<span class="clr-D15B43">*</span>必須フィールド';
document.getElementsByTagName("p")[9].innerHTML = '姓';
document.getElementsByTagName("p")[11].innerHTML = '名';
document.getElementsByTagName("p")[13].innerHTML = '（国番号）';
document.getElementsByTagName("p")[15].innerHTML = '電話番号';
document.getElementsByTagName("p")[18].innerHTML = '[Submit]をクリックすることにより、「個人情報収集に関する声明 」に記載されている利用規約を読み、理解し、同意したことに承諾します。Z.com Tradeから販促用資料を私に電話、またはメールで連絡、送付するかもしれないことを受け入れます。';
document.getElementsByTagName("div")[17].innerHTML = '下記のフォームを記入し、アポイントメントを作成してCS担当と相談しましう。その他、3923-8088に電話するか、<a href="mailto:cs.trade.hk@z.com"><img src="/hk/static/en/common/images/img_mail_cs.png" alt=""></a> かページの一番下にあるオンラインチャットでも予約できます。';
document.getElementsByTagName("th")[0].innerHTML = 'お名前*';
document.getElementsByTagName("th")[1].innerHTML = 'メールアドレス*';
document.getElementsByTagName("th")[2].innerHTML = 'ご希望な面談時間（日付と時刻）*';
document.getElementsByTagName("th")[3].innerHTML = '連絡先*';
document.getElementsByTagName("th")[4].innerHTML = '画像の文字を入力してください*';
